### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by abreulima** [cjkoepke/wp-tailwind#7]
I'm trying to add 
```
function` add_class_to_all_menu_anchors( $atts ) {
    $atts['class'] = 'menu-item-anchor';
 
    return $atts;
}
add_filter( 'nav_menu_link_attributes', 'add_class_to_all_menu_anchors', 10 );
```

inside the functions.php, but I got an error saying.

>  call_user_func_array() expects parameter 1 to be a valid callback, function 'add_class_to_all_menu_anchors' not found or invalid function name in C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php on line 289

> Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\wordpress\wp-includes\class-walker-nav-menu.php on line 205

I tried using another theme and it worked, so it isn't aboud my wordpress, any idea what is happening?

**Comment by cjkoepke** [comment]
@abreulima This is because of the namespace, so you'll need to call the function like this:

`add_filter( 'nav_menu_link_attributes', 'WP_Tailwind\add_class_to_all_menu_anchors', 10 );`

Keep in mind you may have adjusted your namespace from the original demo, but you'll find it on the top of the `functions.php` file on line 6: https://github.com/cjkoepke/wp-tailwind/blob/master/functions.php#L6

For more information on how namespaces work, [read this](https://www.php.net/manual/en/language.namespaces.rationale.php)

**Comment by abreulima** [comment]
Now I'm having problem using some plugins that display content on posts/pages like WPForms and Ninjaforms, nothing is displayed. Is it somehow related to it?

**Comment by cjkoepke** [comment]
@abreulima I would need more detailed information. The namespace itself would not affect that, though.
